config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'portfolio' => 'static_pages#portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalWebsite</title>
	<link href='https://fonts.googleapis.com/css?family=Italiana' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper parent">
    <%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="child">
    <p class="title"><%= link_to "Thomas Harpur", root_path %></p>
    <p class="text left">
      I am a graduate from the University of Birmingham who achieved a 2:1 in Economics with a year in Computer Science. After graduating and spending 6 months working in Canada I began to teach myself Web Development using online resources. I have now reached a stage where I feel confident in my programming skills but would love the opportunity to develop them in a practical environment.
    </p>
    <p class="text left">
      My other main interests are in skiing and music. I have been skiing for around 15 years and I try to get a few weeks in the mountains each year. I have also been playing the drums for around 9 years and try to see music live as often as I can!
    </p>
    <p class="text left">
      I consider myself to be a creative, thoughtful and reliable and I am looking forward to oppurtunities to work in new areas and face new challenges. Thanks for reading about me!
    </p>
	  <p class="title">Contact</p>
	  <p class="text">
	    Email: t.w.harps@gmail.com
	  </p>

	  <p class="text">
	    Mobile: 07891 347062
	  </p>

	  <p class="text">
	    Github: <%= link_to "https://github.com/t-harps", "https://github.com/t-harps" %>
	  </p>
</div>

app/views/static_pages/home.html.erb
<div class="row child">
	<div class="col-md-4 title"><%= link_to "About Me", about_path %></div>
	<div class="col-md-4 title border">
	  <p>Thomas Harpur</p>
	  <p class="text"> 
		  I am a creative graduate looking to use my Computer Science skills and passion for programming to begin a career in the Technology industry.
		</p>
	</div>
  <div class="col-md-4 title"><%= link_to "Portfolio", portfolio_path %></div>
</div>

app/views/static_pages/portfolio.html.erb
<div class="row child">
	<div class="col-md-5">
	  <p class="title">Finished Projects</p>
	  <p class="text"> Personal Website - <%= link_to "GitHub", "https://github.com/t-harps/personal-website" %>
	  </p>
	  <p class="text">
	  <%= link_to "Ski Blog", "https://ski-blog.herokuapp.com" %>
	   - 
	  <%= link_to "GitHub", "https://github.com/t-harps/ski-blog" %>
	  </p>
	</div>
	<div class="col-md-2 title"><%= link_to "Thomas Harpur", root_path %></div>
	<div class="col-md-5">
	  <p class="title">Works in progress</p>
	  <p class="text">
	  <%= link_to "Simple Facebook clone", "https://fakebook-1000.herokuapp.com" %>
	   - 
	  <%= link_to "GitHub", "https://github.com/t-harps/odin-facebook" %>
	  </p>
	</div>
</div>